<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit43e15006db6c3041e7b8c7c57cf04d54
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
        'A' => 
        array (
            'AA\\' => 3,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'AA\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'D' => 
        array (
            'Detection' => 
            array (
                0 => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/namespaced',
            ),
        ),
    );

    public static $classMap = array (
        'Auth' => __DIR__ . '/../..' . '/include/phplib/phplib.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'MLX' => __DIR__ . '/../..' . '/include/mlx.php',
        'MLXCtrl' => __DIR__ . '/../..' . '/include/mlx.php',
        'MLXEvents' => __DIR__ . '/../..' . '/include/mlx.php',
        'MLXGetText' => __DIR__ . '/../..' . '/include/mlx.php',
        'MLXView' => __DIR__ . '/../..' . '/include/mlx.php',
        'Mail_mimePart' => __DIR__ . '/../..' . '/include/htmlMimeMail/mimePart.php',
        'Mobile_Detect' => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/Mobile_Detect.php',
        'PHPGangsta_GoogleAuthenticator' => __DIR__ . '/..' . '/phpgangsta/googleauthenticator/PHPGangsta/GoogleAuthenticator.php',
        'Session' => __DIR__ . '/../..' . '/include/phplib/phplib.php',
        'htmlMimeMail' => __DIR__ . '/../..' . '/include/htmlMimeMail/htmlMimeMail.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit43e15006db6c3041e7b8c7c57cf04d54::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit43e15006db6c3041e7b8c7c57cf04d54::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit43e15006db6c3041e7b8c7c57cf04d54::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit43e15006db6c3041e7b8c7c57cf04d54::$classMap;

        }, null, ClassLoader::class);
    }
}
